name: Issue Manager

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  issue-close:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'arco-design' }}
    steps:
      - name: Needs more info
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          labels: 'ğŸ“„ Need more info'
          inactive-day: 7
          body: |
            ç”±äºè¯¥ issue è¢«æ ‡è®°ä¸ºéœ€è¦æ›´å¤šä¿¡æ¯ï¼Œå´ 7 å¤©æœªæ”¶åˆ°å›åº”ã€‚ç°å…³é—­ issueï¼Œè‹¥æœ‰ä»»ä½•é—®é¢˜ï¼Œå¯è¯„è®ºå›å¤æˆ–ç‚¹å‡»åŠ å…¥[Arco Design é£ä¹¦ç”¨æˆ·ç¾¤](https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=0c2qaa71-ed40-40e7-9389-9f3e182011a5)è¯¢é—®ã€‚

            This issue has been marked as needing more information, but there hasnâ€™t been a response for 7 days, so weâ€™re closing it for now. If you have any questions, feel free to comment here or join the [Arco Design Feishu user group](https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=0c2qaa71-ed40-40e7-9389-9f3e182011a5) to ask for help.

            <img src="https://github.com/user-attachments/assets/65abfd92-38a4-4d34-ad3e-59b9031ca7c3" height="200" />

  check-inactive:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'arco-design' }}
    steps:
      - name: check-inactive
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'check-inactive'
          inactive-label: 'ğŸ’¤ Inactive'
          inactive-day: 30

