name: Issue Labeled

on:
  issues:
    types: [labeled]

permissions:
  contents: read

jobs:
  issue-labeled:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: PR Welcome
        if: github.event.label.name == 'â¤ï¸ PR Welcome' || github.event.label.name == 'ğŸ™ Help wanted'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            æˆ‘ä»¬å®Œå…¨åŒæ„è¯¥æè®®/åé¦ˆï¼Œæ¬¢è¿ç›´æ¥åœ¨æ­¤ä»“åº“åˆ›å»º Pull Request æ¥è§£å†³è¿™ä¸ªé—®é¢˜ã€‚è´¡çŒ®å‰è¯·åŠ¡å¿…é˜…è¯»[è´¡çŒ®æŒ‡å—](https://github.com/arco-design/arco-design-vue/blob/main/CONTRIBUTING.zh-CN.md)ï¼ŒPull Request æ—¶æ ¹æ®éœ€æ”¹åŠ¨å†…å®¹å¡«å†™[é¢„è®¾æ¨¡æ¿](https://github.com/arco-design/arco-design-vue/blob/main/.github/PULL_REQUEST_TEMPLATE.md)ï¼Œæˆ‘ä»¬ä¼šå°½å¿«è¿›è¡Œ Reviewï¼Œæ„Ÿè°¢æ‚¨çš„è´¡çŒ®ï¼

            We agree with this suggestion/feedback and welcome to create a Pull Request in this repository to help address the issue. Before contributing, please make sure to read the [Contributing Guide](https://github.com/arco-design/arco-design-vue/blob/main/CONTRIBUTING.md). When submitting a Pull Request, kindly use the appropriate [PR template](https://github.com/arco-design/arco-design-vue/blob/main/.github/PULL_REQUEST_TEMPLATE.md) based on the changes youâ€™re making. Weâ€™ll review it as soon as possible. Thank you for your contribution!

      - name: Need more info
        if: github.event.label.name == 'ğŸ“„ Need more info'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œæˆ‘ä»¬éœ€è¦ä½ æä¾›æ›´å¤šçš„ä¿¡æ¯æˆ–å¤ç°é“¾æ¥ä»¥ä¾¿äºæˆ‘ä»¬å¸®ä½ æ’æŸ¥å®šä½é—®é¢˜ã€‚7 å¤©å†…æœªè·Ÿè¿›æ­¤ issue å°†ä¼šè¢«è‡ªåŠ¨å…³é—­ã€‚

            Hello @${{ github.event.issue.user.login }}, we need more information or a reproducible link from you to help us investigate and pinpoint the issue. If there is no follow-up within 7 days, this issue will be automatically closed.

      - name: Invalid
        if: github.event.label.name == 'ğŸ™… Invalid'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}, æ‚¨çš„ Issue å·²è¢«æ ‡è®°ä¸ºæ— æ•ˆè€Œè‡ªåŠ¨å…³é—­ï¼ŒåŸå› å¯èƒ½å¦‚ä¸‹ï¼š

            - ä¸ç¬¦åˆæˆ‘ä»¬çš„æ ¼å¼è¦æ±‚ã€å¯èƒ½ç¼ºå°‘è¶³å¤Ÿçš„ä¸Šä¸‹æ–‡æˆ–å…³é”®ä¿¡æ¯ï¼Œæ— æ³•æœ‰æ•ˆè§£å†³é—®é¢˜ã€‚
            - é bug åé¦ˆå’Œéœ€æ±‚è®¨è®º(å¦‚è¯¢é—®å¦‚ä½•ä½¿ç”¨ç­‰é—®é¢˜)ã€‚
            - å®ƒå¯èƒ½æ˜¯å·²æœ‰ Issue çš„é‡å¤é¡¹ã€‚è¯·åœ¨æäº¤æ–°çš„ Issue ä¹‹å‰æ£€æŸ¥ç°æœ‰çš„ Issueã€‚

            å¯ç‚¹å‡»åŠ å…¥[Arco Design é£ä¹¦ç”¨æˆ·ç¾¤](https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=0c2qaa71-ed40-40e7-9389-9f3e182011a5)è¯¢é—®ï¼Œæ„Ÿè°¢æ‚¨çš„ç†è§£ä¸é…åˆï¼

            <img src="https://github.com/user-attachments/assets/65abfd92-38a4-4d34-ad3e-59b9031ca7c3" height="200" />
